spring:
  datasource:
    url: jdbc:h2:file:./data/coupondb
    driver-class-name: org.h2.Driver
    username: sa
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
